using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Hagrid.Core.Domain.Enums
{
    public enum StreetTypeEC
    {
        Nenhum = 0,
        Rua = 1,
        Avenida = 2,
        Praça = 3,
        Outros = 4,
        Aeroporto = 5,
        Alameda = 6,
        Área = 7,
        Beco = 8,
        Bloco = 9,
        Calçada = 10,
        Campo = 11,
        Chácara = 12,
        Colônia = 13,
        Condomínio = 14,
        Conjunto = 15,
        Distrito = 16,
        Escadaria = 17,
        Esplanada = 18,
        Estação = 19,
        Estância = 20,
        Estrada = 21,
        Favela = 22,
        Fazenda = 23,
        Feira = 24,
        Hospital = 25,
        Hotel = 26,
        Jardim = 27,
        Ladeira = 28,
        Lago = 29,
        Lagoa = 30,
        Largo = 31,
        Linha = 32,
        Loteamento = 33,
        Morro = 34,
        Nucleo = 35,
        Parque = 36,
        Passarela = 37,
        Pátio = 38,
        Porto = 39,
        Pousada = 40,
        Povoado = 41,
        Praia = 42,
        Quadra = 43,
        Recanto = 44,
        Residencial = 45,
        Rodovia = 46,
        Setor = 47,
        Sítio = 48,
        Travessa = 49,
        Techo = 50,
        Trevo = 51,
        Vale = 52,
        Vereda = 53,
        Via = 54,
        Viaduto = 55,
        Viela = 56,
        Vila = 57,
    }
}
